# Generated by Django 4.0.5 on 2022-07-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/profile.jpg', upload_to='profile_images'),
        ),
    ]
