# Generated by Django 4.0.5 on 2022-08-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_friends_alter_profile_avatar_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, upload_to='profile_images'),
        ),
    ]
