# Generated by Django 4.0.5 on 2022-08-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_avatar_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
