# Generated by Django 4.0.5 on 2022-08-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
