# Generated by Django 4.0.5 on 2022-08-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_group', '0003_message_delete_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='avatar',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
