# Generated by Django 4.0.5 on 2022-08-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_group', '0005_studygroup_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='slug',
        ),
    ]
