# Generated by Django 4.0.5 on 2022-08-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_group', '0006_remove_studygroup_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
