# Generated by Django 4.0.5 on 2022-07-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='library_name',
        ),
    ]
